"""add campaigns

Revision ID: 7767e766c583
Revises: c890a3b38b9c
Create Date: 2026-08-12 13:19:36.266850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7767e766c583'
down_revision: Union[str, Sequence[str], None] = 'c890a3b38b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('target_amount', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('donations', sa.Column('campaign_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'donations', 'campaigns', ['campaign_id'], ['id'])
    op.drop_column('donations', 'campaign')
    op.add_column('pledges', sa.Column('campaign_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'pledges', 'campaigns', ['campaign_id'], ['id'])
    op.drop_column('pledges', 'campaign')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pledges', sa.Column('campaign', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pledges', type_='foreignkey')
    op.drop_column('pledges', 'campaign_id')
    op.add_column('donations', sa.Column('campaign', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'donations', type_='foreignkey')
    op.drop_column('donations', 'campaign_id')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
