"""add ai action executions

Revision ID: d5f8d5b9bba2
Revises: 994174d3ec8f
Create Date: 2026-08-18 12:36:33.918992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f8d5b9bba2'
down_revision: Union[str, Sequence[str], None] = '994174d3ec8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_action_executions',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('action_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_action_executions')
    # ### end Alembic commands ###
